spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PA5
    username: root
    password: 1043644698
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: GET, POST, PUT, DELETE
      allowed-headers: "*"
